cache('LukyNumber.pl',1,si,2).
cache('LukyNumber.pl',2,3,4).
cache('LukyNumber.pl',1,no,5).
cache('LukyNumber.pl',2,si,3).
cache('LukyNumber.pl',3,5,1).
%------------sort
insert_sort(List,Sorted):-i_sort(List,[],Sorted).
i_sort([],Acc,Acc).
i_sort([H|T],Acc,Sorted):-insert(H,Acc,NAcc),i_sort(T,NAcc,Sorted).   
%insert((X1,X2),[(Y1,Y2)|T],[(Y1,Y2)|NT]):-X2>Y2,insert((X1,X2),T,NT).
%insert((X1,X2),[(Y1,Y2)|T],[(X1,X2),(Y1,Y2)|T]):-X2=<Y2.
insert((X1,X2),[(Y1,Y2)|T],[(Y1,Y2)|NT]):-X2<Y2,insert((X1,X2),T,NT).
insert((X1,X2),[(Y1,Y2)|T],[(X1,X2),(Y1,Y2)|T]):-X2>=Y2.
insert(X,[],[X]).
%---------clear
clearList([],[]):-!.
clearList([(X,Y)],[X]):-!.
clearList([(X,Y)|T],[X|TT]):-clearList(T,TT).
%---------------
orderListCache(X,Y):-insert_sort(X,Z),clearList(Z,Y).
getCache(S,ID,X):-findall((R,C),cache(S,ID,R,C),L),orderListCache(L,X).