MODULE_SESSION:score(0)
MODULE_SESSION:increase(X):-(retract(MODULE_SESSION:score(Y)),Z is X+Y,assert(MODULE_SESSION:score(Z)))
MODULE_SESSION:decrease(X):-(retract(MODULE_SESSION:score(Y)),Z is X-Y,assert(MODULE_SESSION:score(Z)))
MODULE_SESSION:getResult(Ris):-(MODULE_SESSION:score(X),atom_concat('Il tuo punteggio è:',X,Ris))
%######################
MODULE_SESSION:answer(1,'essere->infinite','be',2):-(MODULE_SESSION:increase(1),!)
MODULE_SESSION:answer(1,'essere->infinite',_,1):-MODULE_SESSION:decrease(1)
MODULE_SESSION:answer(2,'essere->past (X Y)','was were',3):-(MODULE_SESSION:increase(3),!)
MODULE_SESSION:answer(2,'essere->past (X Y)',_,2):-MODULE_SESSION:decrease(1)
MODULE_SESSION:answer(3,'essere->past participle','been',4):-(MODULE_SESSION:increase(3),!)
MODULE_SESSION:answer(3,'essere->past participle',_,3):-MODULE_SESSION:decrease(1)
%######################
MODULE_SESSION:answer(4,'sapere->infinite','know',5):-(MODULE_SESSION:increase(1),!)
MODULE_SESSION:answer(4,'sapere->infinite',_,4):-MODULE_SESSION:decrease(1)
MODULE_SESSION:answer(5,'sapere->past','knew',6):-(MODULE_SESSION:increase(3),!)
MODULE_SESSION:answer(5,'sapere->past',_,5):-MODULE_SESSION:decrease(1)
MODULE_SESSION:answer(6,'sapere->past participle','known',7):-(MODULE_SESSION:increase(3),!)
MODULE_SESSION:answer(6,'sapere->past participle',_,6):-MODULE_SESSION:decrease(1)
%######################
MODULE_SESSION:answer(7,'vedere->infinite','see',8):-(MODULE_SESSION:increase(1),!)
MODULE_SESSION:answer(7,'vedere->infinite',_,7):-MODULE_SESSION:decrease(1)
MODULE_SESSION:answer(8,'vedere->past','saw',9):-(MODULE_SESSION:increase(3),!)
MODULE_SESSION:answer(8,'vedere->past',_,8):-MODULE_SESSION:decrease(1)
MODULE_SESSION:answer(9,'vedere->past participle','seen',10):-(MODULE_SESSION:increase(3),!)
MODULE_SESSION:answer(9,'vedere->past participle',_,9):-MODULE_SESSION:decrease(1)
%######################
MODULE_SESSION:answer(10,'trovare->infinite','find',11):-(MODULE_SESSION:increase(1),!)
MODULE_SESSION:answer(10,'trovare->infinite',_,10):-MODULE_SESSION:decrease(1)
MODULE_SESSION:answer(11,'trovare->past','found',12):-(MODULE_SESSION:increase(3),!)
MODULE_SESSION:answer(11,'trovare->past',_,11):-MODULE_SESSION:decrease(1)
MODULE_SESSION:answer(12,'trovare->past participle','found',13):-(MODULE_SESSION:increase(1),!)
MODULE_SESSION:answer(12,'trovare->past participle',_,12):-MODULE_SESSION:decrease(1)
%######################
MODULE_SESSION:answer(13,'sentirsi->infinite','feel',14):-(MODULE_SESSION:increase(1),!)
MODULE_SESSION:answer(13,'sentirsi->infinite',_,13):-MODULE_SESSION:decrease(1)
MODULE_SESSION:answer(14,'sentirsi->past','felt',15):-(MODULE_SESSION:increase(3),!)
MODULE_SESSION:answer(14,'sentirsi->past',_,14):-MODULE_SESSION:decrease(1)
MODULE_SESSION:answer(15,'sentirsi->past participle','felt',16):-(MODULE_SESSION:increase(1),!)
MODULE_SESSION:answer(15,'sentirsi->past participle',_,15):-MODULE_SESSION:decrease(1)
%######################
MODULE_SESSION:answer(16,'cadere->infinite','fall',17):-(MODULE_SESSION:increase(1),!)
MODULE_SESSION:answer(16,'cadere->infinite',_,16):-MODULE_SESSION:decrease(1)
MODULE_SESSION:answer(17,'cadere->past','fell',18):-(MODULE_SESSION:increase(3),!)
MODULE_SESSION:answer(17,'cadere->past',_,17):-MODULE_SESSION:decrease(1)
MODULE_SESSION:answer(18,'cadere->past participle','fallen',-1):-(MODULE_SESSION:increase(3),!)
MODULE_SESSION:answer(18,'cadere->past participle',_,18):-MODULE_SESSION:decrease(1)